---
site_name: Sitodo
site_url: https://sitodo-example.herokuapp.com
theme:
  name: readthedocs
nav:
  - Home:
      - Course Overview: README.md
  - Day One:
      - Initialise Project: bootcamp/day-1/init-spring.md
      - Hello, TDD: bootcamp/day-1/hello-tdd.md
      - Automation: bootcamp/day-1/qa-automation.md
      - Create a Basic Todo List: bootcamp/day-1/basic-list.md
      - Recap: bootcamp/day-1/end-day-1.md
      # 1 jam course, 1 jam mengarahkan
      # 4 jam mengerjakan sesuai instruksi + 2 jam additional
      #   (bagi peserta yang butuh tantangan/butuh bantuan tambahan)
  - Day Two:
      - TBD: bootcamp/day-2/README.md
      # 1 jam course, 1 jam mengarahkan
      # 4 jam mengerjakan sesuai instruksi + 2 jam additional
      #   (bagi peserta yang butuh tantangan/butuh bantuan tambahan)
      # Ide untuk hari kedua: badges, README, GitHub Actions
  #- Extra Challenges:
  #    - Functional Test: extra/functional-test.md
  #    - Analyse Code Quality: extra/codeql.md
  #    - User Authentication: extra/auth.md
