---
site_name: Sitodo
site_url: https://sitodo-example.herokuapp.com
nav:
  - Home:
      - Course Overview: index.md
      - Table of Contents: toc.md
  - Course Setup:
      - Overview: setup/index.md
      - Local Development Environment: setup/environment.md
      - Project Scaffolding: setup/scaffolding.md
      - GitHub: setup/github.md
      - Fly: setup/fly.md
      - GitHub Actions: setup/ci.md
  - Implement Basic Feature:  # Implement stateless feature: landing page
      - Overview: feature-1/index.md
      - Test-Driven Development: feature-1/tdd.md
      - Outside-in TDD 1 - Functional Test: feature-1/functional-test.md
      - Outside-in TDD 2 - Unit Test in Mocked Environment: feature-1/unit-test-mock.md
      - Outside-in TDD 3 - Pure Unit Test: feature-1/unit-test.md
  - Quality Assurance & Automation:
      - Overview: qa/index.md
      - Test Automation on GitHub Actions: qa/test.md
      - Code Quality: qa/codeql.md
      - Continuous Integration & Deployment: qa/cicd.md
  - Todo List:  # Implement stateful feature: todo list
      - Overview:
