---
site_name: Sitodo
site_url: https://sitodo-example.herokuapp.com
theme:
  name: readthedocs
nav:
  - Home:
      - Course Overview: index.md
      - Table of Contents: toc.md
  - Course Setup:
      - Overview: setup/index.md
      - Local Development Environment: setup/environment.md
      - Project Scaffolding: setup/scaffolding.md
      - GitHub: setup/github.md
      - Deploy to PaaS: setup/deploy.md
  - TDD-style Hello, World:
      - Overview: feature-1/index.md
      - Test-Driven Development: feature-1/tdd.md
      - Unit Test: feature-1/unit-test.md
      - Unit Test in Mocked Environment: feature-1/unit-test-mock.md
  - Quality Assurance & Automation:
      - Overview: qa/index.md
      - Automate Test Execution using GitHub Actions: qa/test.md
      - Automate Deployment using GitHub Actions: qa/deploy.md
  - Implement Basic Feature:
      - Overview: feature-2/index.md
      - Data Persistence Layer: feature-2/data.md
      - Business Logic Layer: feature-2/business.md
      - Presentation Layer: feature-2/presentation.md
  - Extra Challenges:
      - Functional Test: extra/functional-test.md
      - Analyse Code Quality: extra/codeql.md
      - User Authentication: extra/auth.md
      - PostgreSQL Database: extra/postgres.md
