---
site_name: Sitodo
site_url: https://sitodo-example.herokuapp.com
theme:
  name: readthedocs
nav:
  - Home:
      - Course Overview: index.md
      - Table of Contents: toc.md
  - Day One:
      - Overview: day-1/README.md
      - Hello, TDD: day-1/hello-tdd.md
      - Automation: day-1/qa-automation.md
      - Create a Todo List (Part 1): day-1/todo-list.md
      # 1 jam course, 1 jam mengarahkan
      # 4 jam mengerjakan sesuai instruksi + 2 jam additional
      #   (bagi peserta yang butuh tantangan/butuh bantuan tambahan)
  - Day Two:
      - Overview: day-2/README.md
      - Create a Todo List (Part 2): day-2/todo-list-continued.md
      - Refactor Model to Use PostgreSQL Database: day-2/postgres.md
      # 1 jam course, 1 jam mengarahkan
      # 4 jam mengerjakan sesuai instruksi + 2 jam additional
      #   (bagi peserta yang butuh tantangan/butuh bantuan tambahan)
      # Ide untuk hari kedua: badges, README, GitHub Actions
  - Extra Challenges:
      - Functional Test: extra/functional-test.md
      - Analyse Code Quality: extra/codeql.md
      - User Authentication: extra/auth.md
