---
name: Continuous Integration (CI)

on: [push, pull_request]

jobs:
  test:
    name: Run all tests

    runs-on: ubuntu-22.04

    env:
      # Based on the Maven CI/CD template from GitLab:
      # https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Maven.gitlab-ci.yml
      # It is recommended to use these variables to reduce noise in the logs
      MAVEN_OPTS: >
        -Dhttps.protocols=TLSv1.2
        -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN
        -Dorg.slf4j.simpleLogger.showDateTime=true
        -Djava.awt.headless=true
      MAVEN_CLI_OPTS: >
        --batch-mode
        --errors
        --fail-at-end
        --show-version
        -DinstallAtEnd=true
        -DdeployAtEnd=true

    # Based on the example at:
    # https://github.com/actions/example-services/blob/master/.github/workflows/postgres-service.yml
    services:
      postgres:
        image: docker.io/library/postgres:14.5-alpine3.16
        env:
          POSTGRES_USER: sitodo
          POSTGRES_PASSWORD: 9BZ4S4Jt
          POSTGRES_DB: sitodo
        ports:
          - 5432/tcp
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"
          cache: "maven"
      - name: Install Firefox ESR
        uses: browser-actions/setup-firefox@latest
        with:
          firefox-version: "latest-esr"
      - name: Run unit tests
        env:
          SPRING_DATASOURCE_URL: "jdbc:postgresql://localhost:${{ job.services.postgres.ports[5432] }}/sitodo"
          SPRING_DATASOURCE_USERNAME: sitodo
          SPRING_DATASOURCE_PASSWORD: 9BZ4S4Jt
        run: mvn $MAVEN_CLI_OPTS test -Dgroups=unit -Djacoco.destFile=target/jacoco-unit.exec
      - name: Run functional tests
        env:
          SPRING_DATASOURCE_URL: "jdbc:postgresql://localhost:${{ job.services.postgres.ports[5432] }}/sitodo"
          SPRING_DATASOURCE_USERNAME: sitodo
          SPRING_DATASOURCE_PASSWORD: 9BZ4S4Jt
        run: |
          mvn $MAVEN_CLI_OPTS test -Dgroups=e2e -Djacoco.destFile=target/jacoco-functional.exec
