---
name: Reporting

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  report:
    name: Publish test reports
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Download CI reports
        uses: dawidd6/action-download-artifact@v2.9.0
        with:
          branch: main
          name: surefire-jacoco-reports
          path: tmp
          workflow: ci.yml
      - name: Download BDD test reports
        uses: dawidd6/action-download-artifact@v2.9.0
        with:
          branch: main
          name: serenity-reports
          path: tmp
          workflow: bdd.yml
      - name: Organise test reports
        run: |
          mkdir -p target/site
          mv tmp/surefire-jacoco-reports/surefire target/site/surefire
          mv tmp/surefire-jacoco-reports/jacoco target/site/jacoco
          mv tmp/serenity-reports/serenity target/site/serenity
          cp .github/pages/index.html target/site/index.html
      - run: ls tmp/
      - run: ls -R target/site
      - name: Publish test reports
        uses: JamesIves/github-pages-deploy-action@v4.5.0
        with:
          branch: gh-pages
          folder: target/site
